[package]
name = "chickenwire"
version = "0.1.0"
authors = ["smith7 <smith7@uchicago.edu>"]
edition = "2018"

[dependencies]
petgraph = "0.4.13"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "cribench_coordinate"
harness = false
